# Generated by Django 4.2.4 on 2023-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Заказчик'), ('gai', 'Фрилансер')], max_length=100, null=True),
        ),
    ]
