# Generated by Django 4.2.4 on 2023-12-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Foydalanuchi'), ('gai', 'Gai')], max_length=100, null=True),
        ),
    ]
