# Generated by Django 4.2.4 on 2024-01-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(max_length=8)),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'main_sms_code',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='dispatch_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
