# Generated by Django 4.2.4 on 2023-12-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('teck_number', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_number', models.CharField(max_length=150)),
                ('violation_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('violation_clause', models.CharField(max_length=250)),
                ('violation_description', models.TextField()),
                ('violation_address', models.TextField()),
                ('fine_amount', models.FloatField()),
                ('fine_fast', models.IntegerField()),
                ('fine_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_payment', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road.car')),
            ],
        ),
    ]
