# Generated by Django 4.2.4 on 2023-12-28 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='fine_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fine',
            name='violation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 26, 11, 28, 23, 386405, tzinfo=datetime.timezone.utc)),
        ),
    ]
