# Generated by Django 4.2.4 on 2023-12-29 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0006_alter_fine_violation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='violation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 10, 39, 47, 32114, tzinfo=datetime.timezone.utc)),
        ),
    ]
