# Generated by Django 4.2.4 on 2024-01-04 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0007_alter_fine_violation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='violation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 12, 18, 37, 20322, tzinfo=datetime.timezone.utc)),
        ),
    ]
