# Generated by Django 4.2.4 on 2024-01-18 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0008_alter_fine_violation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fine',
            name='violation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 50, 43, 708738, tzinfo=datetime.timezone.utc)),
        ),
    ]
