# Generated by Django 4.2.4 on 2024-01-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0010_alter_fine_violation_date_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_cvc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fine',
            name='violation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 14, 1, 19, 224282, tzinfo=datetime.timezone.utc)),
        ),
    ]
