# Generated by Django 4.2.4 on 2024-01-20 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0011_card_card_cvc_alter_fine_violation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fine',
            name='violation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 11, 46, 27, 489197, tzinfo=datetime.timezone.utc)),
        ),
    ]
